---
title: "Test Table"
author: "Nic Wheeler"
date: 2017-09-15T21:13:14-05:00
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
output: html_document
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

This is a test table, in preparation for Paul's table.

```{r, echo = FALSE, context="server"}

library(DT)
library(shiny)
library(tidyverse)

df <- read.csv("~/Box Sync/GitHub/airs_table/data.csv", header = TRUE) %>%
  select(-X.1, -X.2)

shinyApp(
  
  ui <- fluidPage(
  title = 'Use the DT package in shiny',
  h1('A Table Using Client-side Processing'),
  fluidRow(
    column(2),
    column(8, DT::dataTableOutput('tbl_a')),
    column(2)
  )#,
  # h1('A Table Using Server-side Processing'),
  # fluidRow(
  #   column(2),
  #   column(8, DT::dataTableOutput('tbl_b')),
  #   column(2)
  # )
  ),
  
 server <- function(input, output, session) {
  output$tbl_a = DT::renderDataTable(df, server = FALSE)
  output$tbl_b = DT::renderDataTable(df)
},
  
  options = list(height = 500)
)
```



